# Generated by Django 4.2.6 on 2023-11-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0002_votacionmateria_delete_votacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='nombre',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
