# Generated by Django 4.2.6 on 2024-05-02 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0003_alter_materia_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materia',
            old_name='fk_id_carrera',
            new_name='carrera',
        ),
    ]
