# Generated by Django 5.0 on 2024-05-26 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0004_rename_fk_id_carrera_materia_carrera'),
        ('profesor', '0008_remove_profesor_materia'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='profesor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materia_profesor', to='profesor.profesor'),
        ),
    ]
