# Generated by Django 5.0 on 2024-05-26 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0005_materia_profesor'),
        ('profesor', '0009_remove_profesor_carrera_remove_profesor_institucion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='profesor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materia_profesor', to='profesor.profesor'),
        ),
    ]
