# Generated by Django 4.2.6 on 2023-11-10 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumno', '0001_initial'),
        ('carrera', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='fk_id_carrera',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='carrera.carrera'),
        ),
    ]
