# Generated by Django 4.2.6 on 2023-11-10 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, default='Tecnicatura Superior', max_length=50, null=True)),
                ('duracion', models.PositiveIntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Votacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(default=None)),
                ('carrera', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='carrera.carrera')),
            ],
        ),
    ]
