# Generated by Django 4.2.6 on 2023-11-10 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carrera', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institucion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='votacion',
            name='usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='votaciones_carrera_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carrera',
            name='fk_id_institucion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='carreras_institucion', to='institucion.institucion'),
        ),
    ]
