# Generated by Django 4.2.6 on 2023-11-10 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carrera', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotacionCarrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(default=None)),
                ('carrera', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='carrera.carrera')),
                ('usuario', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='votaciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Votacion',
        ),
    ]
