# Generated by Django 4.2.6 on 2023-11-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrera', '0003_votacioncarrera_delete_votacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='titulo',
            field=models.CharField(blank=True, default='Tecnicatura Superior', max_length=150, null=True),
        ),
    ]
