# Generated by Django 5.0.4 on 2024-04-30 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrera', '0005_carrera_img_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='img_perfil',
            field=models.ImageField(blank=True, default='perfiles/Carreras/Carreras-Perfil.jpeg', null=True, upload_to='perfiles/carrera_uploads/'),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='titulo',
            field=models.CharField(blank=True, default='Técnico Superior', max_length=150, null=True),
        ),
    ]
