# Generated by Django 4.2.6 on 2024-05-02 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrera', '0006_alter_carrera_img_perfil_alter_carrera_titulo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrera',
            old_name='fk_id_institucion',
            new_name='institucion',
        ),
    ]
