# Generated by Django 4.2.6 on 2024-05-03 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrera', '0007_rename_fk_id_institucion_carrera_institucion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrera',
            old_name='titulo',
            new_name='nombre',
        ),
    ]
