# Generated by Django 4.2.6 on 2024-05-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrera', '0008_rename_titulo_carrera_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='img_perfil',
            field=models.ImageField(blank=True, default='Carreras/Carreras-Perfil.jpeg', null=True, upload_to='carrera_uploads/'),
        ),
    ]
