# Generated by Django 4.2.6 on 2023-11-10 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursada', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('fk_id_cursada', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='opiniones_cursadas', to='cursada.cursada')),
                ('fk_id_usuario', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='opiniones_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
