# Generated by Django 4.2.6 on 2024-05-03 04:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('opinion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opinion',
            old_name='fk_id_usuario',
            new_name='autor',
        ),
        migrations.RemoveField(
            model_name='opinion',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='opinion',
            name='fk_id_cursada',
        ),
        migrations.AddField(
            model_name='opinion',
            name='calificacion',
            field=models.PositiveIntegerField(default=5, help_text='Puntuación de 1 a 5 estrellas', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='opinion',
            name='contenido',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='opinion',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='opinion',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='opinion',
            name='titulo',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
