# Generated by Django 5.0.4 on 2024-04-05 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0002_alter_customuser_tipo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='edad',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='genero',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='institucion',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='img_perfil',
            field=models.ImageField(blank=True, default='ProyectoFinal/static/imagenes/Iconos/UserProfile.png', null=True, upload_to='perfiles/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tipo_usuario',
            field=models.CharField(blank=True, choices=[('Alumno', 'Alumno'), ('Institución', 'Institución'), ('Profesor', 'Profesor'), ('Visitante', 'Visitante')], default='Alumno', max_length=20, null=True),
        ),
    ]
