# Generated by Django 5.0.4 on 2024-04-09 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0003_customuser_edad_customuser_genero_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='edad',
        ),
        migrations.AddField(
            model_name='customuser',
            name='fecha_de_nacimiento',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='O', max_length=1, null=True),
        ),
    ]
