# Generated by Django 5.0 on 2024-05-16 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0006_alter_customuser_img_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='img_perfil',
            field=models.ImageField(blank=True, default='UserProfile.png', null=True, upload_to='user_uploads/'),
        ),
    ]
