# Generated by Django 5.0 on 2024-05-27 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0007_alter_customuser_img_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='nombre',
            field=models.CharField(blank=True, default='Anonimo', max_length=100, null=True),
        ),
    ]
