# Generated by Django 4.2.6 on 2023-11-16 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0003_institucion_url'),
        ('profesor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='id_institucion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='institucion.institucion'),
        ),
    ]
