# Generated by Django 4.2.6 on 2024-05-01 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0003_rename_fk_id_usuario_profesor_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='img_perfil',
            field=models.ImageField(blank=True, default='perfiles/Profesores/ProfesorDefault.jpeg', null=True, upload_to='perfiles/profesores_uploads/'),
        ),
    ]
