# Generated by Django 4.2.6 on 2024-05-15 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0007_alter_institucion_img_perfil'),
        ('profesor', '0005_alter_profesor_img_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='institucion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='institucion.institucion'),
        ),
    ]
