# Generated by Django 5.0 on 2024-05-26 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0007_profesor_carrera'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='materia',
        ),
    ]
