# Generated by Django 5.0 on 2024-05-26 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrera', '0009_alter_carrera_img_perfil'),
        ('institucion', '0007_alter_institucion_img_perfil'),
        ('profesor', '0008_remove_profesor_materia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='carrera',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='institucion',
        ),
        migrations.AddField(
            model_name='profesor',
            name='carrera',
            field=models.ManyToManyField(related_name='profesores_carrera', to='carrera.carrera'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='institucion',
            field=models.ManyToManyField(related_name='profesores_institucion', to='institucion.institucion'),
        ),
    ]
