# Generated by Django 5.0 on 2024-05-27 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0010_alter_profesor_institucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='img_perfil',
            field=models.ImageField(blank=True, default='Profesores/ProfesorDefault.jpeg', null=True, upload_to='perfiles/profesores_uploads/'),
        ),
    ]
