# Generated by Django 4.2.6 on 2023-11-10 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='IFTS', max_length=50, null=True)),
                ('ubicacion', models.CharField(blank=True, default='Argentina', max_length=50, null=True)),
                ('fk_id_usuario', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='instituciones_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
