# Generated by Django 4.2.6 on 2023-11-14 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0002_alter_institucion_nombre_alter_institucion_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucion',
            name='url',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
