# Generated by Django 5.0.4 on 2024-04-30 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0004_institucion_img_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucion',
            name='img_perfil',
            field=models.ImageField(blank=True, default='perfiles/IFTS/IFTS18-FRONT.jpg', null=True, upload_to='perfiles/ifts_uploads/'),
        ),
    ]
