# Generated by Django 4.2.6 on 2024-05-02 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0005_alter_institucion_img_perfil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institucion',
            old_name='fk_id_usuario',
            new_name='usuario',
        ),
    ]
