# Generated by Django 4.2.6 on 2024-05-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0006_rename_fk_id_usuario_institucion_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucion',
            name='img_perfil',
            field=models.ImageField(blank=True, default='IFTS/IFTS18-FRONT.jpg', null=True, upload_to='ifts_uploads/'),
        ),
    ]
