# Generated by Django 5.0 on 2024-05-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0007_alter_institucion_img_perfil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institucion',
            old_name='ubicacion',
            new_name='direccion',
        ),
        migrations.AddField(
            model_name='institucion',
            name='coordenadas',
            field=models.CharField(blank=True, default='-34.603722,-58.381592', max_length=250, null=True),
        ),
    ]
