# Generated by Django 5.0 on 2024-05-30 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0008_rename_ubicacion_institucion_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucion',
            name='img_perfil',
            field=models.ImageField(blank=True, default='perfiles/IFTS/IFTS-Default.png', null=True, upload_to='perfiles/ifts_uploads/'),
        ),
    ]
